In [1]:
import pandas as pd
df = pd.read_csv("https://gist.githubusercontent.com/tiangechen/b68782efa49a16edaf07dc2cdaa855ea/raw/0c794a9717f18b094eabab2cd6a6b9a226903577/movies.csv")
df['Genre'] = df['Genre'].replace(['Comdy','comedy','Romence','romance'],['Comedy','Comedy','Romance','Romance'], inplace=False)
df.isnull().value_counts()
df.drop_duplicates()
df

                                  Film    Genre  ... Worldwide Gross  Year
0           Zack and Miri Make a Porno  Romance  ...         $41.94   2008
1                      Youth in Revolt   Comedy  ...         $19.62   2010
2   You Will Meet a Tall Dark Stranger   Comedy  ...         $26.66   2010
3                         When in Rome   Comedy  ...         $43.04   2010
4                What Happens in Vegas   Comedy  ...        $219.37   2008
..                                 ...      ...  ...             ...   ...
72                 Across the Universe  Romance  ...         $29.37   2007
73                       A Serious Man    Drama  ...         $30.68   2009
74                  A Dangerous Method    Drama  ...          $8.97   2011
75                          27 Dresses   Comedy  ...        $160.31   2008
76                (500) Days of Summer   Comedy  ...         $60.72   2009

[77 rows x 8 columns]

In [2]:
df[df["Genre"] == "Comedy"].count()

Film                 43
Genre                43
Lead Studio          43
Audience score %     43
Profitability        43
Rotten Tomatoes %    43
Worldwide Gross      43
Year                 43
dtype: int64

In [3]:
# 1 
# Can you print the first 10 records. v1


df.iloc[:10, :]

                                 Film      Genre  ... Worldwide Gross  Year
0          Zack and Miri Make a Porno    Romance  ...         $41.94   2008
1                     Youth in Revolt     Comedy  ...         $19.62   2010
2  You Will Meet a Tall Dark Stranger     Comedy  ...         $26.66   2010
3                        When in Rome     Comedy  ...         $43.04   2010
4               What Happens in Vegas     Comedy  ...        $219.37   2008
5                 Water For Elephants      Drama  ...        $117.09   2011
6                              WALL-E  Animation  ...        $521.28   2008
7                            Waitress    Romance  ...         $22.18   2007
8                 Waiting For Forever    Romance  ...          $0.03   2011
9                     Valentine's Day     Comedy  ...        $217.57   2010

[10 rows x 8 columns]

In [4]:
# 1 
# Can you print the first 10 records. v2


df.head(10)

                                 Film      Genre  ... Worldwide Gross  Year
0          Zack and Miri Make a Porno    Romance  ...         $41.94   2008
1                     Youth in Revolt     Comedy  ...         $19.62   2010
2  You Will Meet a Tall Dark Stranger     Comedy  ...         $26.66   2010
3                        When in Rome     Comedy  ...         $43.04   2010
4               What Happens in Vegas     Comedy  ...        $219.37   2008
5                 Water For Elephants      Drama  ...        $117.09   2011
6                              WALL-E  Animation  ...        $521.28   2008
7                            Waitress    Romance  ...         $22.18   2007
8                 Waiting For Forever    Romance  ...          $0.03   2011
9                     Valentine's Day     Comedy  ...        $217.57   2010

[10 rows x 8 columns]

In [5]:
# 2
# What are the data types of the columns. 

df.dtypes

Film                  object
Genre                 object
Lead Studio           object
Audience score %       int64
Profitability        float64
Rotten Tomatoes %      int64
Worldwide Gross       object
Year                   int64
dtype: object

In [6]:
# 3
# Count of Animation movies.
# Hint: use the count() function

df[df['Genre'] == "Animation"]["Film"].count()

4

In [7]:
# 4
# Show the Comedy movies in the year 2007.

df[(df["Genre"] == 'Comedy') & (df["Year"] == 2007)]

                  Film   Genre  ... Worldwide Gross  Year
18  The Heartbreak Kid  Comedy  ...        $127.77   2007
36     No Reservations  Comedy  ...         $92.60   2007
51      License to Wed  Comedy  ...         $69.31   2007
54          Knocked Up  Comedy  ...           $219   2007
62     Good Luck Chuck  Comedy  ...         $59.19   2007
69           Enchanted  Comedy  ...        $340.49   2007

[6 rows x 8 columns]

In [8]:
# 5
# Count of Animation movies with more than 70% Audience Score.

df[(df['Audience score %'] > 70) & (df['Genre'] == 'Animation') ]["Film"].count()

2

In [9]:
# 5 v2
# Count of Animation movies with more than 70% Audience Score.
Animation_up_70_df = df[(df["Genre"] == "Animation") & (df["Audience score %"] > 70)]
Animation_up_70_df_count = (Animation_up_70_df["Film"]).count()
print(Animation_up_70_df_count)

2

In [10]:
# 6
# Show the list of top 5 movies based on profitability.

df.sort_values(by = "Profitability", ascending = False).head(5)

                                  Film    Genre  ... Worldwide Gross  Year
68                           Fireproof    Drama  ...         $33.47   2008
60  High School Musical 3: Senior Year   Comedy  ...        $252.04   2008
14         The Twilight Saga: New Moon    Drama  ...        $709.82   2009
7                             Waitress  Romance  ...         $22.18   2007
12                            Twilight  Romance  ...        $376.66   2008

[5 rows x 8 columns]

In [11]:
# 7 v1
# Show the top 5 Comedy movies approved by the audience. (hint : Audience Score)

df.sort_values(by = "Audience score %", ascending = False ) [df['Genre'] == 'Comedy'].head(5)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.

                    Film   Genre  ... Worldwide Gross  Year
54            Knocked Up  Comedy  ...           $219   2007
76  (500) Days of Summer  Comedy  ...         $60.72   2009
27      Sex and the City  Comedy  ...        $415.25   2008
69             Enchanted  Comedy  ...        $340.49   2007
71             Beginners  Comedy  ...         $14.31   2011

[5 rows x 8 columns]

In [12]:
# 7 v2
# Show the top 5 Comedy movies approved by the audience. (hint : Audience Score)
df[df["Genre"] == "Comedy"].sort_values(by= ["Audience score %"], ascending =False).head(5)

                    Film   Genre  ... Worldwide Gross  Year
54            Knocked Up  Comedy  ...           $219   2007
76  (500) Days of Summer  Comedy  ...         $60.72   2009
27      Sex and the City  Comedy  ...        $415.25   2008
71             Beginners  Comedy  ...         $14.31   2011
69             Enchanted  Comedy  ...        $340.49   2007

[5 rows x 8 columns]

In [13]:
# Prepare the Data on ["Wordlwide Gross"] for the assignment

# 1 Replace non compatible characters
Worldwide_Gross_string = df["Worldwide Gross"].str.replace("$", "")

# 2 Convert the string into numeric
Worldwide_Gross_num = pd.to_numeric(Worldwide_Gross_string)

# 3 Substitute columns or create a new one
df["Worldwide Gross"] = Worldwide_Gross_num

In [14]:
# Extra Assignments
# Show the movies with more than 70% Audience Score & greater than $350 Worldwide Gross.

df[(df["Audience score %"] > 70) & (df["Worldwide Gross"] > 350)]

                           Film      Genre  ... Worldwide Gross  Year
6                        WALL-E  Animation  ...          521.28  2008
12                     Twilight    Romance  ...          376.66  2008
14  The Twilight Saga: New Moon      Drama  ...          709.82  2009
22                      Tangled  Animation  ...          355.01  2010
27             Sex and the City     Comedy  ...          415.25  2008
45                   Mamma Mia!     Comedy  ...          609.47  2008
46                   Mamma Mia!     Comedy  ...          609.47  2008

[7 rows x 8 columns]

In [16]:
# Show the movies  produced by Disney with more than 70% Audience Score & greater than $350 Worldwide Gross .
# V1
df[(df["Audience score %"] > 70) & (df["Worldwide Gross"] > 350) & (df["Lead Studio"] == "Disney")]

       Film      Genre Lead Studio  ...  Rotten Tomatoes %  Worldwide Gross  Year
6    WALL-E  Animation      Disney  ...                 96           521.28  2008
22  Tangled  Animation      Disney  ...                 89           355.01  2010

[2 rows x 8 columns]

In [ ]:
# Show the movies  produced by Disney with more than 70% Audience Score & greater than $350 Worldwide Gross .
# V2

up70_up350_df = df[(df["Audience score %"] > 70) & (df['Worldwide Gross'] > 350)]
up70_up350_df_disney = up70_up350_df[up70_up350_df["Lead Studio"] == "Disney"]
up70_up350_df_disney

       Film      Genre Lead Studio  ...  Rotten Tomatoes %  Worldwide Gross  Year
6    WALL-E  Animation      Disney  ...                 96           521.28  2008
22  Tangled  Animation      Disney  ...                 89           355.01  2010

[2 rows x 8 columns]

In [17]:
# Count of Animation movies with more than 70% Audience Score.

df[(df["Genre"] == "Animation") & (df["Audience score %"] > 70)]["Film"].count()

2

In [18]:
# Show the list of top 5 movies based on profitability.
df.sort_values(by="Profitability", ascending=False).head(5)

                                  Film    Genre  ... Worldwide Gross  Year
68                           Fireproof    Drama  ...           33.47  2008
60  High School Musical 3: Senior Year   Comedy  ...          252.04  2008
14         The Twilight Saga: New Moon    Drama  ...          709.82  2009
7                             Waitress  Romance  ...           22.18  2007
12                            Twilight  Romance  ...          376.66  2008

[5 rows x 8 columns]

In [19]:
# Show the top 5 Comedy movies approved by the audience. (hint : Audience Score)
df[df["Genre"]=="Comedy"].sort_values(by="Audience score %", ascending=False).head(5)

                    Film   Genre  ... Worldwide Gross  Year
54            Knocked Up  Comedy  ...          219.00  2007
76  (500) Days of Summer  Comedy  ...           60.72  2009
27      Sex and the City  Comedy  ...          415.25  2008
71             Beginners  Comedy  ...           14.31  2011
69             Enchanted  Comedy  ...          340.49  2007

[5 rows x 8 columns]

In [20]:
# Which Genre is favored the most by the Audience ?
df.sort_values(by="Audience score %", ascending=False)["Genre"].head(1)

74    Drama
Name: Genre, dtype: object

In [21]:
# Top 5 movie names by Rotten Tomato Score.
df.sort_values(by="Rotten Tomatoes %", ascending=False)["Film"].head(5)

6                WALL-E
43    Midnight in Paris
69            Enchanted
54           Knocked Up
22              Tangled
Name: Film, dtype: object

In [22]:
# Top 3 high gross Romance movies produced by Disney after 2008

Romance_Disney_up2008_df = df[(df["Genre"]=="Romance") & (df["Lead Studio"] == "Disney") & (df["Year"] > 2008)]
Romance_Disney_up2008_df_3best = Romance_Disney_up2008_df.sort_values (by="Worldwide Gross", ascending=False).head(3)
Romance_Disney_up2008_df_3best

Empty DataFrame
Columns: [Film, Genre, Lead Studio, Audience score %, Profitability, Rotten Tomatoes %, Worldwide Gross, Year]
Index: []

In [23]:
# How many Lead Studios are present in the dataframe? v1
# (Hint: use the function value_counts() which applies to category)

Lead_Studio_c = df["Lead Studio"].value_counts()
Lead_Studio_c.count()

13

In [24]:
# How many Lead Studios are present in the dataframe? v2
# Only with funtion .count()

#1 Created a new Pandas Serie
#2 Delete duplicates
#3 Count the Lead Studios with the funtion .count()

Lead_Studio = df["Lead Studio"]
Lead_Studio_no_dup = Lead_Studio.drop_duplicates()
Lead_Studio_no_dup.count()

13

In [25]:
# Top 5 profitable movies produced by Disney after 2008 (measured by Profitability index)
df[(df["Lead Studio"] == "Disney") & (df["Year"] > 2008)].sort_values(by="Profitability", ascending=False).head(5)

                 Film      Genre  ... Worldwide Gross  Year
16       The Proposal     Comedy  ...          314.70  2009
64  Gnomeo and Juliet  Animation  ...          193.97  2011
65  Gnomeo and Juliet  Animation  ...          193.97  2011
22            Tangled  Animation  ...          355.01  2010
3        When in Rome     Comedy  ...           43.04  2010

[5 rows x 8 columns]

In [26]:
# Most & Least Frequent lead studio in the dataset in terms of occurances. v1

print("The most frequent Lead studio on the Dataset is:")
print(df["Lead Studio"].max())
print("\nThe least frequent Lead studio on the Dataset is:")
print(df["Lead Studio"].min())

The most frequent Lead studio on the Dataset is:
Warner Bros.

The least frequent Lead studio on the Dataset is:
20th Century Fox

In [28]:
# Most & Least Frequent lead studio in the dataset in terms of occurances. v2
# Together but with error
print(df["Lead Studio"].max()) 
print("&") 
print(df["Lead Studio"].min())

Warner Bros.
&
20th Century Fox

In [31]:
# Most and Least profitable Lead Studio. (Take an average of all Profitability measures grouped by Lead studios)

df_prof = df.groupby("Lead Studio")["Profitability"].mean()
print("Most profitable:")
print(df_prof.sort_values().tail(1))

print("\nLeast profitable:")
print(df_prof.sort_values().head(1))

Most profitable:
Lead Studio
Summit    6.377962
Name: Profitability, dtype: float64

Least profitable:
Lead Studio
The Weinstein Company    1.221114
Name: Profitability, dtype: float64

In [33]:
# Top 5 lead studios with audience score greater than 70%. v1
df_audience = df.groupby("Lead Studio")["Audience score %"].mean()
df_audience.sort_values(ascending=False).head(5)

# If the mean is calculated, there is just one Lead Studio with audience Score greater than 70%

Lead Studio
Summit                   73.200000
Sony                     69.500000
Disney                   69.375000
Fox                      69.000000
The Weinstein Company    68.666667
Name: Audience score %, dtype: float64

In [34]:
# Top 5 lead studios with audience score greater than 70%. v2
df_audience = df.groupby("Lead Studio")["Audience score %"].max()
df_audience.sort_values(ascending=False).head()

# Taking the highest audience score for each film.

Lead Studio
Independent              89
Disney                   89
The Weinstein Company    84
Sony                     84
Universal                83
Name: Audience score %, dtype: int64

In [35]:
# Count of least Frequent Genre with Rotten Tomato score more than 50%.
rotten_50 = df[df["Rotten Tomatoes %"] > 50]
rotten_50_genre = rotten_50.groupby("Genre").count()
rotten_50_sorted = rotten_50_genre.sort_values(by="Rotten Tomatoes %").head(1)
rotten_50_sorted["Film"]

Genre
Fantasy    1
Name: Film, dtype: int64

In [36]:
# Ranking of Fox studio for Comedy movies based on Audience Score. v1
comedy = df[df["Genre"]=="Comedy"]
comedy_leadstudio = comedy.groupby("Lead Studio").mean()
comedy_leadstudio_rank = comedy_leadstudio.rank(ascending= False)["Audience score %"]
comedy_leadstudio_rank["Fox"]

2.0

In [37]:
# Ranking of Fox studio for Comedy movies based on Audience Score. v2
comedy_mov = df[df["Genre"] == "Comedy"]
df_AudienceScore_ave_Studio = pd.DataFrame(comedy_mov.groupby('Lead Studio')['Audience score %'].mean())
df_AudienceScore_ave_Studio['Audience score %'].rank(ascending=False) ["Fox"]

2.0

In [38]:
# Count of each genre of movies produced by Independent. (use groupby() )
df[df["Lead Studio"]=="Independent"].groupby("Genre").count()["Film"]

Genre
Comedy     7
Drama      4
Romance    8
Name: Film, dtype: int64